CREATE TABLE PAGOS(
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de Creación de la fila',
	UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de modificación',
	UPDATE_USER VARCHAR(200) NOT NULL DEFAULT '' COMMENT 'Usuario que registro el cambio',
	ID_PAGO INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Identificador del Pago',
	ID_ORDEN INT UNSIGNED NOT NULL COMMENT 'Identificador de la Orden',
	ID_TRABAJO INT UNSIGNED NOT NULL COMMENT 'Identificador del trabajo',
	METODO_PAGO VARCHAR(15) NOT NULL COMMENT 'Identificador del método de pago',
	FECHA_DE_PAGO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha del Pago',
	ESTADO_DEL_PAGO VARCHAR(15) NOT NULL COMMENT 'Estado del Pago',
	PRECIO_FINAL FLOAT(10,2) NOT NULL COMMENT 'El valor del pago',
	PRIMARY KEY (ID_PAGO)
	);
	
ALTER TABLE PAGOS ADD INDEX (ID_ORDEN);
ALTER TABLE PAGOS ADD INDEX (ID_TRABAJO);
ALTER TABLE PAGOS ADD INDEX (METODO_PAGO);
ALTER TABLE PAGOS ADD INDEX (ESTADO_DEL_PAGO);