CREATE TABLE FECHAS_TENTATIVAS(
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de Creación de la fila',
	UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de modificación',
	UPDATE_USER VARCHAR(200) NOT NULL DEFAULT '' COMMENT 'Usuario que registro el cambio',	
	ID_FECHAS_TENTATIVAS INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la Fecha Tentativa',
	ID_ORDEN INT UNSIGNED NOT NULL COMMENT 'Identificador de la Orden',
	FECHA_TENTATIVA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha Tentativa',
	PRIMARY KEY (ID_FECHAS_TENTATIVAS)
	);
	
ALTER TABLE FECHAS_TENTATIVAS ADD INDEX (ID_ORDEN);