CREATE TABLE METODO_PAGO(
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de Creación de la fila',
	UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de modificación',
	UPDATE_USER VARCHAR(200) NOT NULL DEFAULT '' COMMENT 'Usuario que registro el cambio',
	METODO_PAGO VARCHAR(15) NOT NULL COMMENT 'Código del Método de Pago',
	DESCRIPCION VARCHAR(350) NOT NULL COMMENT 'Descripción',
	);