CREATE TABLE LANZAMIENTO(
	LANZAMIENTO_ID INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Identificador del usuario',
	LANZAMIENTO_EMAIL VARCHAR(150) NOT NULL UNIQUE DEFAULT '' COMMENT 'Correo electrónico del Usuario',
	PRIMARY KEY (LANZAMIENTO_ID)
	);