CREATE TABLE PROVEEDOR(
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de Creación de la fila',
	UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de modificación',
	UPDATE_USER VARCHAR(200) NOT NULL DEFAULT '' COMMENT 'Usuario que registro el cambio',
	ID_PROVEEDOR INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Identificador del proveedor',
	NOMBRE VARCHAR(150) NOT NULL COMMENT 'Nombre del Proveedor',
	CATEGORIA VARCHAR(150) NOT NULL COMMENT 'Categoría del Proveedor',
	TELEFONO INT(8) NOT NULL COMMENT 'Telefono del Proveedor',
	CELULAR INT(9) NOT NULL COMMENT 'Celular del Proveedor',
	DIRECCION VARCHAR(350) NOT NULL COMMENT 'Dirección',
	COORDENADAS VARCHAR(150) NOT NULL COMMENT 'Coordenadas',
	EMAIL VARCHAR(150) NOT NULL UNIQUE DEFAULT '' COMMENT 'Correo electrónico',
	PRIMARY KEY (ID_PROVEEDOR),
	);

ALTER TABLE PROVEEDOR ADD INDEX (CATEGORIA);
ALTER TABLE PROVEEDOR ADD INDEX (TELEFONO);	
ALTER TABLE PROVEEDOR ADD INDEX (CELULAR);	
ALTER TABLE PROVEEDOR ADD INDEX (EMAIL);