C:\Users\Usuario\gitAlamano3004\Alamano\src\scripts

CREATE TABLE ORDEN(
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de Creación de la fila',
	UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de modificación',
	UPDATE_USER VARCHAR(200) NOT NULL DEFAULT '' COMMENT 'Usuario que registro el cambio',
	UPDATE_PROGRAM VARCHAR(200) NOT NULL DEFAULT '' COMMENT 'El programa, clase que realizo el insert',	
	ID_ORDEN INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la Orden',
	ID_TRABAJO INT UNSIGNED NOT NULL COMMENT 'Identificador del trabajo',
	METODO_PAGO VARCHAR(15) NOT NULL DEFAULT '' COMMENT 'Identificador del método de pago',
	ID_USUARIO INT UNSIGNED NOT NULL COMMENT 'Identificador del usuario',
	ESTADO VARCHAR(15) NOT NULL DEFAULT '' COMMENT 'Estado de la Orden',
	FECHA_DE_EJECUCION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de ejecución de la Orden',
	CELULAR_CONTACTO INT(9) UNSIGNED NOT NULL COMMENT 'Celular de Contacto',
	DURACION DECIMAL(2,2) UNSIGNED NOT NULL COMMENT 'Duración de la Orden',
	PRECIO_FINAL FLOAT(10,2) NOT NULL COMMENT 'El valor del precio final de la orden',
	PRECIO_UNITARIO FLOAT(10,2) NOT NULL COMMENT 'El valor del precio unitario',
	DIRECCION_SERVICIO VARCHAR(350) NOT NULL COMMENT 'Dirección del Servicio',
	ACLARACIONES VARCHAR(350) NOT NULL DEFAULT '' COMMENT 'Aclaraciones',
	PRIMARY KEY (ID_ORDEN)
	);
	
ALTER TABLE ORDEN ADD INDEX (ID_TRABAJO);
ALTER TABLE ORDEN ADD INDEX (METODO_PAGO);
ALTER TABLE ORDEN ADD INDEX (ID_USUARIO);
ALTER TABLE ORDEN ADD INDEX (CELULAR_CONTACTO);