CREATE TABLE SERVICIO(
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de Creación de la fila',
	UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de modificación',
	UPDATE_USER VARCHAR(200) NOT NULL DEFAULT '' COMMENT 'Usuario que registro el cambio',
	ID_SERVICIO INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Identificador del servicio',
	NOMBRE VARCHAR(150) NOT NULL COMMENT 'Nombre del Servicio',
	CATEGORIA VARCHAR(150) NOT NULL COMMENT 'Categoria',
	PRIMARY KEY (ID_SERVICIO)
	);   
	
ALTER TABLE SERVICIO ADD INDEX (CATEGORIA);