CREATE TABLE ESTADO_ORDENES(
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de Creación de la fila',
	UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de modificación',
	UPDATE_USER VARCHAR(200) NOT NULL DEFAULT '' COMMENT 'Usuario que registro el cambio',
	CODIGO_ESTADO VARCHAR(15) NOT NULL COMMENT 'Código del Estado',
	NOMBRE VARCHAR(150) NOT NULL COMMENT 'Nombre del Estado',
	DESCRIPCION VARCHAR(350) NOT NULL COMMENT 'Descripción del Estado',
	PRIMARY KEY (CODIGO_ESTADO)
	);